

/* eslint-disable @next/next/no-page-custom-font */
import { Open_Sans } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Layout from "@/layout/Layout";
import store from "@/redux/store";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



import Providers from "@/redux/provider";
import SessionProviders from "@/redux/sessionProvider";


const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "25 MetreKare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={openSans.className}>
        <SessionProviders >
          <Providers>
            <ToastContainer />
            <Layout>{children}</Layout>
          </Providers>
        </SessionProviders>
      </body>
    </html>
  );
}

